### ISSUE TITLE
ANT 버튼을 누를 경우 메인 페이지로 이동하는 기능

### ISSUE THREAD

**Issue by HyeockJinKim** [CNU-ANT/ANT-Cave#50]
ANT 버튼을 누를 경우 메인 페이지로 이동하는 기능이 있는 것이 좋을 듯 합니다. 

![image](https://user-images.githubusercontent.com/26498366/39453026-5329a7ae-4d0f-11e8-90c6-3f7aeea3d4e3.png)

**Comment by HyeockJinKim** [comment]
제가 하겠습니다.

**Comment by inspire12** [comment]
넵
